# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QFileDialog, QTableWidget, QTableWidgetItem
from dadosCliente import Ui_formDadosCliente
import mysql.connector
import pandas
import variaveisControle


class Ui_formCliente(object):
    def setupUi(self, formCliente):
        formCliente.setObjectName("formCliente")
        formCliente.resize(823, 559)
        self.bt_adiocionar = QtWidgets.QPushButton(formCliente)
        self.bt_adiocionar.setGeometry(QtCore.QRect(10, 0, 89, 91))
        self.bt_adiocionar.setStyleSheet("image: url(:/icon_adicionar/imagens/icons/adicionar.png)")
        self.bt_adiocionar.setText("")
        self.bt_adiocionar.setObjectName("bt_adiocionar")
        self.bt_alterar = QtWidgets.QPushButton(formCliente)
        self.bt_alterar.setGeometry(QtCore.QRect(100, 0, 89, 91))
        self.bt_alterar.setStyleSheet("image: url(:/icon_alterar/imagens/icons/alterar.png)")
        self.bt_alterar.setText("")
        self.bt_alterar.setObjectName("bt_alterar")
        self.bt_consultar = QtWidgets.QPushButton(formCliente)
        self.bt_consultar.setGeometry(QtCore.QRect(190, 0, 89, 91))
        self.bt_consultar.setStyleSheet("image: url(:/icon_consultar/imagens/icons/consultar.png)")
        self.bt_consultar.setText("")
        self.bt_consultar.setObjectName("bt_consultar")
        self.bt_excluir = QtWidgets.QPushButton(formCliente)
        self.bt_excluir.setGeometry(QtCore.QRect(280, 0, 89, 91))
        self.bt_excluir.setStyleSheet("image: url(:/icon_excluir/imagens/icons/excluir.png)")
        self.bt_excluir.setText("")
        self.bt_excluir.setObjectName("bt_excluir")
        self.bt_retornar = QtWidgets.QPushButton(formCliente)
        self.bt_retornar.setGeometry(QtCore.QRect(730, 0, 89, 91))
        self.bt_retornar.setStyleSheet("image: url(:/icon_retornar/imagens/icons/retornar.png)")
        self.bt_retornar.setText("")
        self.bt_retornar.setObjectName("bt_retornar")
        self.bt_pesquisar = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisar.setGeometry(QtCore.QRect(550, 130, 21, 25))
        self.bt_pesquisar.setStyleSheet("image: url(:/icon_pesquisar/imagens/icons/pesquisar.png)")
        self.bt_pesquisar.setText("")
        self.bt_pesquisar.setObjectName("bt_pesquisar")
        self.bt_pesquisarGeral = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisarGeral.setGeometry(QtCore.QRect(580, 130, 21, 25))
        self.bt_pesquisarGeral.setStyleSheet("image: url(:/icon_geral/imagens/icons/filtro.png)")
        self.bt_pesquisarGeral.setText("")
        self.bt_pesquisarGeral.setObjectName("bt_pesquisarGeral")
        self.tb_cliente = QtWidgets.QTableWidget(formCliente)
        self.tb_cliente.setGeometry(QtCore.QRect(0, 200, 821, 341))
        self.tb_cliente.setObjectName("tb_cliente")
        self.tb_cliente.setColumnCount(4)
        self.tb_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(3, item)
        self.lb_nomeCliente = QtWidgets.QLabel(formCliente)
        self.lb_nomeCliente.setGeometry(QtCore.QRect(120, 130, 91, 17))
        self.lb_nomeCliente.setObjectName("lb_nomeCliente")
        self.txt_nomeCliente = QtWidgets.QLineEdit(formCliente)
        self.txt_nomeCliente.setGeometry(QtCore.QRect(220, 130, 321, 25))
        self.txt_nomeCliente.setObjectName("txt_nomeCliente")

        self.retranslateUi(formCliente)
        QtCore.QMetaObject.connectSlotsByName(formCliente)

    def retranslateUi(self, formCliente):
        _translate = QtCore.QCoreApplication.translate
        formCliente.setWindowTitle(_translate("formCliente", "Form"))
        self.bt_adiocionar.setToolTip(_translate("formCliente", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_alterar.setToolTip(_translate("formCliente", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_consultar.setToolTip(_translate("formCliente", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_excluir.setToolTip(_translate("formCliente", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_retornar.setToolTip(_translate("formCliente", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tb_cliente.horizontalHeaderItem(0)
        item.setText(_translate("formCliente", "ID:"))
        item = self.tb_cliente.horizontalHeaderItem(1)
        item.setText(_translate("formCliente", "Nome:"))
        item = self.tb_cliente.horizontalHeaderItem(2)
        item.setText(_translate("formCliente", "Telefone:"))
        item = self.tb_cliente.horizontalHeaderItem(3)
        item.setText(_translate("formCliente", "Cidade:"))
        self.lb_nomeCliente.setText(_translate("formCliente", "Nome Cliente:"))

        #Botoes do sistema
        self.bt_retornar.clicked.connect(lambda: self.sairTela(formCliente))
        self.bt_pesquisarGeral.clicked.connect(self.consultarGeral)
        self.bt_pesquisar.clicked.connect(self.pesquisarCliente)
        self.bt_adiocionar.clicked.connect(self.cadastrarCliente)

    #Funcoes sistema
    def sairTela(self, formCliente):
        formCliente.close()


    def consultarGeral(self):
        #Conexao com o banco
        mydb = mysql.connector.connect(
            host = variaveisControle.host,
            user = variaveisControle.user,
            password = variaveisControle.password,
            database = variaveisControle.database
        )
        mycursor = mydb.cursor()
        mycursor.execute("SELECT * FROM cliente")
        myresult = mycursor.fetchall()

        #tabela
        df = pandas.DataFrame(myresult, columns=['ID', 'Nome', 'Telefone', 'Cidade'])
        self.all_data = df

        #Carregar na tabela
        numRows = len(self.all_data.index)
        self.tb_cliente.setColumnCount(len(self.all_data.columns))
        self.tb_cliente.setRowCount(numRows)
        self.tb_cliente.setHorizontalHeaderLabels(self.all_data.columns)

        for i in range(numRows):
            for j in range(len(self.all_data.columns)):
                self.tb_cliente.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i, j])))

        self.tb_cliente.resizeColumnsToContents()
        self.tb_cliente.resizeRowsToContents()

        mycursor.close()

    def pesquisarCliente(self):
        mydb = mysql.connector.connect(
            host = variaveisControle.host,
            user = variaveisControle.user,
            password = variaveisControle.password,
            database = variaveisControle.database
        )
        mycursor = mydb.cursor()
        nomeConsulta = self.txt_nomeCliente.text()
        consultaSQL = "SELECT * FROM cliente WHERE nome like '" + nomeConsulta + "%'"
        mycursor.execute(consultaSQL)
        myresult = mycursor.fetchall()

        #tabela
        df = pandas.DataFrame(myresult, columns=['ID', 'Nome', 'Telefone', 'Cidade'])
        self.all_data = df

        #Carregar na tabela
        numRows = len(self.all_data.index)
        self.tb_cliente.setColumnCount(len(self.all_data.columns))
        self.tb_cliente.setRowCount(numRows)
        self.tb_cliente.setHorizontalHeaderLabels(self.all_data.columns)

        for i in range(numRows):
            for j in range(len(self.all_data.columns)):
                self.tb_cliente.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i, j])))

        self.tb_cliente.resizeColumnsToContents()
        self.tb_cliente.resizeRowsToContents()

        mycursor.close()


    def cadastrarCliente(self):
        self.formDadosCliente = QtWidgets.QWidget()
        self.ui = Ui_formDadosCliente()
        self.ui.setupUi(self.formDadosCliente)
        self.formDadosCliente.show()


import icon_adicionar
import icon_alterar
import icon_consultar
import icon_excluir
import icon_geral
import icon_pesquisar
import icon_retornar


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formCliente = QtWidgets.QWidget()
    ui = Ui_formCliente()
    ui.setupUi(formCliente)
    formCliente.show()
    sys.exit(app.exec_())
